// Echte Begriffe/Tokens aus den Case-Studies dieser Seite — keine erfundenen
// Buzzwords. Für die Matrix-Glitch-Textur im Hintergrund (rein dekorativ).
export const HERO_FRAGMENTS = [
  "DOCKER",
  "CADDY",
  "POSTGRES",
  "DSGVO",
  "RCON",
  "TURNSTILE",
  "GUARDRAIL",
  "N8N",
  "KILL_SWITCH",
  "SSH",
  "MATRIX",
  "OAUTH2",
  "OPTUNA",
  "ROCKSDB",
  "DISCORD",
  "DRIZZLE",
  "ZNTX_DB",
  "SCOPE_GUARD",
  "PAPER_TRADING",
  "INVITE_ONLY",
  "0x9F2A",
  "200 OK",
] as const;
